# Generated by Django 4.0.4 on 2022-09-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('Programming for beginners', 'Course1'), ('Programming for programmers', 'Course2'), ('Programming for advanced programmers', 'Course3')], default='Programming for beginners', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectLearning.user'),
        ),
    ]
