# Generated by Django 4.0.4 on 2022-09-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0005_forum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
