# Generated by Django 4.0.4 on 2022-09-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0006_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectLearning.person'),
        ),
    ]
