# Generated by Django 4.0.4 on 2022-09-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLearning', '0010_forum_user_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
    ]
